server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      default-zone: ${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false

---
spring:
  profiles: peer1

eureka:
  instance:
    hostname: peer1
  client:
    service-url:
      default-zone: http://peer2/eureka/

---
spring:
  profiles: peer2

eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      default-zone: http://peer1/eureka/

---
