eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: learning-spring-boot
        output:
          destination: learning-spring-boot
          group: comments
          content-type: application/json
  application:
    name: images
  servlet:
    multipart:
      max-file-size: 10MB